title: Homelab Dashboard

background:
  image: ADD_IMAGE_URL
  blur: lg
  saturate: 100
  brightness: 80
  opacity: 30

theme: dark
color: slate

useEqualHeights: true

layout:
  Network Operations:
    header: true
    style: row
    columns: 4
  Core Services:
    header: true
    style: row
    columns: 4
  Testing:
    header: true
    style: row
    columns: 4
  Storage:
    header: true
    style: row
    columns: 4
  Media Services:
    header: true
    style: row
    columns: 4
  Automation:
    header: true
    style: row
    columns: 4
